// <auto-generated />
using System;
using BroGarage.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BroGarage.API.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260521184556_Net10Sync")]
    partial class Net10Sync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BroGarage.API.Data.Entities.CarEntity", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CarTypeEntity", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("TypeId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TypeName");

                    b.ToTable("CarTypes");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Representative")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CustomerTypeEntity", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("TypeId");

                    b.ToTable("CustomerTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            TypeName = "Cá nhân",
                            UpdatedUserId = 0
                        },
                        new
                        {
                            TypeId = 2,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            TypeName = "Doanh nghiệp",
                            UpdatedUserId = 0
                        });
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.ManufacturerEntity", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("ManufacturerId");

                    b.HasIndex("ManufacturerName")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderDetailEntity", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHideProduct")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<long>("AdvancePayment")
                        .HasColumnType("bigint");

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOutActual")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateOutEstimated")
                        .HasColumnType("date");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Discount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiredInDate")
                        .HasColumnType("date");

                    b.Property<string>("InternalNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsInvoice")
                        .HasColumnType("bit");

                    b.Property<decimal>("ODOCurrent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("ODONext")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ODOUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(3, 2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CarId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("StatusId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TypeId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderStatusEntity", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            StatusName = "Báo giá",
                            UpdatedUserId = 0
                        },
                        new
                        {
                            StatusId = 2,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            StatusName = "Đang sửa chữa",
                            UpdatedUserId = 0
                        },
                        new
                        {
                            StatusId = 3,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            StatusName = "Chờ giao xe",
                            UpdatedUserId = 0
                        },
                        new
                        {
                            StatusId = 4,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            StatusName = "Hoàn thành",
                            UpdatedUserId = 0
                        });
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderTypeEntity", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("TypeId");

                    b.ToTable("OrderTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            TypeName = "Bảo dưỡng",
                            UpdatedUserId = 0
                        },
                        new
                        {
                            TypeId = 2,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 1,
                            TypeName = "Sửa chữa",
                            UpdatedUserId = 0
                        });
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationInDate")
                        .HasColumnType("date");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ExpirationInDate");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.TemplateDetailEntity", b =>
                {
                    b.Property<int>("TemplateDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateDetailId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("TemplateDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateDetails");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.TemplateEntity", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<int?>("CarTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("YearOfManufactureFrom")
                        .HasColumnType("int");

                    b.Property<int>("YearOfManufactureTo")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.HasIndex("CarTypeId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<long>("CreatedTimeStamp")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedTime = new TimeSpan(0, 20, 14, 0, 0),
                            CreatedTimeStamp = 1666210440L,
                            CreatedUserId = 0,
                            FullName = "Quản trị viên",
                            PasswordHash = "ea871309f6e9a5490bd909aaf2f80f57a7dca87397af1d454c95652fc4201deb",
                            Salt = "ztSiY7kw5joGzZcwdtKqztSiY7kw5joGzZcwdtKqztSiY7kw5joGzZcwdtKqztSiY7kw5joGzZcwdtKqztSiY7kw5joGzZcwdtKqztSiY7kw5joGzZcwdtKqztSiY7kw",
                            UpdatedUserId = 0,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CarEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.CarTypeEntity", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeId");

                    b.HasOne("BroGarage.API.Data.Entities.CustomerEntity", "Customer")
                        .WithMany("Cars")
                        .HasForeignKey("CustomerId");

                    b.Navigation("CarType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CarTypeEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("CarTypes")
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CustomerEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.CustomerTypeEntity", "CustomerType")
                        .WithMany("Customers")
                        .HasForeignKey("TypeId");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderDetailEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.OrderEntity", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("BroGarage.API.Data.Entities.ProductEntity", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.CarEntity", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId");

                    b.HasOne("BroGarage.API.Data.Entities.OrderStatusEntity", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId");

                    b.HasOne("BroGarage.API.Data.Entities.TemplateEntity", "Template")
                        .WithMany("Orders")
                        .HasForeignKey("TemplateId");

                    b.HasOne("BroGarage.API.Data.Entities.OrderTypeEntity", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("TypeId");

                    b.Navigation("Car");

                    b.Navigation("OrderType");

                    b.Navigation("Status");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.TemplateDetailEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.ProductEntity", "Product")
                        .WithMany("TemplateDetails")
                        .HasForeignKey("ProductId");

                    b.HasOne("BroGarage.API.Data.Entities.TemplateEntity", "Template")
                        .WithMany("TemplateDetails")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Product");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.TemplateEntity", b =>
                {
                    b.HasOne("BroGarage.API.Data.Entities.CarTypeEntity", "CarType")
                        .WithMany("Templates")
                        .HasForeignKey("CarTypeId");

                    b.Navigation("CarType");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CarEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CarTypeEntity", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.CustomerTypeEntity", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("CarTypes");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderStatusEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.OrderTypeEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.ProductEntity", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("TemplateDetails");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.TemplateEntity", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("TemplateDetails");
                });

            modelBuilder.Entity("BroGarage.API.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
